export const EnvKey = Object.freeze({
  DB_URI: "DATABASE_CONNECTION_URI",
  DB_NAME: "DATABASE_NAME",
  DB_USERNAME: "DATABASE_USERNAME",
  DB_PASSWORD: "DATABASE_PASSWORD",
  JWT_KEY: "JWT_SECRET_KEY",
  JWT_REFRESH_KEY: "JWT_REFRESH_KEY",
  JWT_LIMIT: "JWT_LIMIT",
  MODE: "MODE",
  SECURE: "SECURE",
});
